title: Luckyfox.fi
description: > # this means to ignore newlines until "baseurl:"
  Luckyfox
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luckyfox.fi" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

sass:
    sass_dir: _sass
