title: Luckyfox | Foxiest digital masterminds
description: Foxiest digital masterminds
baseurl: ""
url: "https://luckyfox.fi"

# Build settings
markdown: kramdown
theme: minima

sass:
    sass_dir: _sass
